name: Code Quality and Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage codecov

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml -o coverage.xml

      - name: Upload coverage to Codecov
        run: codecov -f coverage.xml
